### ISSUE TITLE
[Event] Beyond Code - A non-technical playbook for the interview grind

### ISSUE THREAD

**Issue by jamesi8086** [JuniorDevSingapore/developers-gym#2]
**Title**: Beyond Code - A non-technical playbook for the interview grind
 
**Date(s)**: 4th Jan 2020

**Description**:
Over the past 6 years I've been helping friends prepare for technical interviews with purely technical exercises. Just a year ago I had to go through job-hunting myself and decided to thoroughly analyze various non-technical aspects throughout my journey.

This (intense) session with both mini-exercises and stories would serve as both a motivational driver and informative session for attendees. This is also the first time I would share this.

https://www.linkedin.com/in/yongkimleng/

Rough outline:
- Impostor Syndrome
- Depression
- Finding Purpose
- Psych
- Personal Goals
- Company Culture
- Negotiation
- Acceptance

**Requirements** *(check any that apply)*:

- [X] We require a venue for the event
- [ ] We require food for the event
- [ ] We require teaching assistants for the event

**Comment by miccheng** [comment]
Event: https://www.meetup.com/Junior-Developers-Singapore/events/267505139/
Video: https://engineers.sg/v/3876
Slides: https://drive.google.com/file/d/1pvpstHjMomekJTIxyUTngU1TERctjZ6w/view?usp=sharing
Photos: https://www.meetup.com/Junior-Developers-Singapore/photos/30641770/487858167/
